add_newline = true

[directory]
style = "bold green"

[hostname]
ssh_only = false
disabled = false

# Replace the "❯" symbol in the prompt with "λ"
[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[V](bold green)"

[python]
# symbol = " "
style = "green bold"

[git_status]
style = "blue bold"

#[battery]
#full_symbol = ""

[[battery.display]]
threshold = 10
style = "bold red"

[gcloud]
disabled = true

[custom.starship_gitlab]
command = "starship-gitlab -m dev"
directories = [".git"]
format = "[$output]($style)"
