# only include what is present
for bin_dir in `cat ~/.bin_dirs`; do
    if [ -d "$HOME/$bin_dir" ] ; then
        export PATH="$PATH:$HOME/$bin_dir"
    fi
done

export BROWSER="firefox"
export PAGER="nvimpager"
export BAT_THEME="gruvbox-dark"
export EDITOR="nvim"
export TERMINAL="alacritty"
export LANG=en_US.UTF-8
export SHELL=/bin/zsh
export _JAVA_AWT_WM_NONREPARENTING=1
export PF_SOURCE=/home/maxim/dokumente/proj/pfetch/addon.sh

export ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
export ZVM_VI_VISUAL_ESCAPE_BINDKEY=jk
export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_USER_DEFAULT
export ZVM_TERM=alacritty-256color
