# History
HISTFILE=~/.zshist
HISTSIZE=10000
SAVEHIST=10000

# Shell options
setopt autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
zstyle :compinstall filename '/home/maxim/.zshrc'

autoload -Uz compinit
compinit

source $HOME/.aliases

eval "$(starship init zsh)"
#eval "$(fasd --init zsh-hook posix-alias)"

export PF_INFO="ascii title os kernel uptime pkgs init shell wm editor keymap memory palette"
#pfetch

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set cursor shapes
function zle-keymap-select zle-line-init zle-line-finish {
  case $KEYMAP in
    vicmd)      print -n -- "\E]50;CursorShape=0\C-G";; # block cursor
    viins|main) print -n -- "\E]50;CursorShape=2\C-G";; # underscore cursor
  esac

  zle reset-prompt
  zle -R
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select
# set cursor shapes END

if [ -f "/usr/share/zsh/scripts/zplug/init.zsh" ] ; then
    source /usr/share/zsh/scripts/zplug/init.zsh

    zplug "jeffreytse/zsh-vi-mode"
    zplug "zsh-users/zsh-syntax-highlighting"
    zplug "greymd/docker-zsh-completion"
    zplug "ptavares/zsh-z"

    # Install plugins if there are plugins that have not been installed
    if ! zplug check; then
        printf "Install? [y/N]: "
        if read -q; then
            echo; zplug install
        fi
    fi

    # Then, source plugins and add commands to $PATH
    zplug load
fi

if [ -f "$HOME/.zshcustom/gico.completion.zsh" ] ; then
  source "$HOME/.zshcustom/gico.completion.zsh"
fi

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#
#  # place this after nvm initialization!
# autoload -U add-zsh-hook
# load-nvmrc() {
#     local node_version="$(nvm version)"
#     local nvmrc_path="$(nvm_find_nvmrc)"
#
#     if [ -n "$nvmrc_path" ]; then
#         local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
#
#         if [ "$nvmrc_node_version" = "N/A" ]; then
#             nvm install
#         elif [ "$nvmrc_node_version" != "$node_version" ]; then
#             nvm use
#         fi
#     elif [ "$node_version" != "$(nvm version default)" ]; then
#         echo "Reverting to nvm default version"
#         nvm use default
#     fi
# }
# add-zsh-hook chpwd load-nvmrc
# load-nvmrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/maxim/downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/maxim/downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/maxim/downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/maxim/downloads/google-cloud-sdk/completion.zsh.inc'; fi
