#!/bin/sh
export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1
setxkbmap us -variant dvorak-intl
xrdb ~/.Xresources.gruvbox
xrandr --output HDMI-0 --right-of eDP-1-1 --auto
doas systemctl restart openntpd
dbus-launch --sh-syntax xmonad || exec /home/maxim/.config/init_wm.sh
