---
- name: Setup zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "~/.zshrc"
    state: hard
    force: true

- name: Setup zshenv
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshenv"
    dest: "~/.zshenv"
    state: hard
    force: true

- name: Setup zprofile
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zprofile"
    dest: "~/.zprofile"
    state: hard
    force: true

- name: Setup zprofile
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/aliases"
    dest: "~/.aliases"
    state: hard
    force: true

- name: Setup bin directories
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/bin_dirs"
    dest: "~/.bin_dirs"
    state: hard
    force: true

- name: Setup starship
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.toml"
    dest: "~/.config/starship.toml"
    state: hard
    force: true

- name: zsh custom config dir
  file:
    path: "~/.zshcustom"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Setup gico completion
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/gico.completion.zsh"
    dest: "~/.zshcustom/gico.completion.zsh"
    state: hard
    force: true

- name: ngrok config dir
  file:
    path: "~/.ngrok2"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Setup ngrok
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/ngrok.yml"
    dest: "~/.ngrok2/ngrok.yml"
    state: hard
    force: true
