colors:
  primary:
    foreground : '0xebdbb2'
    background : '0x202020'

  normal:
    black:   '0x161616'
    red:     '0xcc241d'
    green:   '0x689d6a'
    yellow:  '0xEEBD35'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  bright:
    black:   '0x282828'
    red:     '0xfb4934'
    green:   '0x98971a'
    yellow:  '0xfabd2f'
    blue:    '0x7fa2ac'
    magenta: '0xD4879C'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
