- name: Configure xplr
  file:
    src: "{{ dotfiles_home }}/roles/xplr/files/xplr"
    dest: "~/.config/xplr"
    state: link
    force: yes

- name: nnn config that is used by xplr
  file:
    src: "{{ dotfiles_home }}/roles/xplr/files/nnn"
    dest: "~/.config/nnn"
    state: link
    force: yes
