---
- name: create 'aur-bulider' user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: allow aur_builder to run sudo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: install paru
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  become: true
  become_user: aur_builder

- name: Configure paru
  file:
    src: "{{ dotfiles_home }}/roles/pacman/files/paru.conf"
    dest: "/etc/paru.conf"
    state: hard
    force: true
  become: true
  become_user: root

- name: pacman -Syu
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true
  become_user: root
  become_method: sudo
