- name: setup .config
  file:
    path: ~/.config
    state: directory

- name: Configure alacritty
  file:
    src: "{{ dotfiles_home }}/roles/alacritty/files/alacritty"
    dest: "~/.config/alacritty"
    state: link
    force: yes

