- name: Provide doas.conf
  file:
    src: "{{ dotfiles_home }}/roles/doas/files/doas.conf"
    dest: "/etc/doas.conf"
    state: hard
    force: yes
    group: root
    owner: root
  become: yes
  become_user: root
  become_method: sudo
