- name: Install packages from repo
  community.general.pacman:
    name: opendoas
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Provide doas.conf
  file:
    src: "{{ dotfiles_home }}/roles/doas/files/doas.conf"
    dest: "/etc/doas.conf"
    state: hard
    force: yes
