---
- name: Configure xmonad and xmobar
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/xmonad"
    dest: "~/.xmonad"
    state: link
    force: true

- name: Install xinitrc
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/xinitrc"
    dest: "~/.xinitrc"
    state: hard
    mode: 0755
    force: true

- name: Install .profile
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/profile"
    dest: "~/.profile"
    mode: 0755
    state: hard
    force: true

- name: Install down scripts
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/down_scripts"
    dest: "~/.config/down_scripts"
    mode: 0755
    state: link
    force: true

- name: Install Xresources
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/Xresources"
    dest: "~/.Xresources"
    mode: 0755
    state: hard
    force: true

- name: Install Xresources gruvbox
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/Xresources.gruvbox"
    dest: "~/.Xresources.gruvbox"
    mode: 0755
    state: hard
    force: true

- name: Install Xresources tokyonight
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/Xresources.tokyonight"
    dest: "~/.Xresources.tokyonight"
    mode: 0755
    state: hard
    force: true

- name: Install Xsetup_0 to theme xdm
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/Xsetup_0"
    dest: "/etc/X11/xdm/Xsetup_0"
    mode: 0755
    state: hard
    force: true
  become: true

- name: Recompile xmonad
  command: "xmonad --recompile"
